const gearData = {
    "legs": [
        { id: "l1", name: "Champion Boots", level: 60, rarity: "Legendary", image: "assets/gear/legs.png", stats: { combat: { rng_atk: 56, army_atk: 14, army_hp: 30.8 }, economy: { travel_speed: 70 } } },
        { id: "l2", name: "Champion Greaves", level: 60, rarity: "Legendary", image: "assets/gear/legs.png", stats: { combat: { cav_atk: 56, army_atk: 14, army_hp: 30.8 }, economy: { travel_speed: 70 } } },
        { id: "l3", name: "Champion Stride", level: 60, rarity: "Legendary", image: "assets/gear/legs.png", stats: { combat: { inf_atk: 56, army_atk: 14, army_hp: 30.8 }, economy: { travel_speed: 70 } } },
        { id: "l4", name: "Blizzard Pants", level: 60, rarity: "Epic", image: "assets/gear/legs.png", stats: { combat: { rng_atk: 42, cav_atk: 42, army_def: 14, army_hp: 16.8 }, economy: {} } },
        { id: "l5", name: "Storm Tasset", level: 60, rarity: "Epic", image: "assets/gear/legs.png", stats: { combat: { inf_atk: 42, cav_atk: 42, army_def: 28, army_hp: 14 }, economy: {} } },
        { id: "l6", name: "Dragon Talon", level: 60, rarity: "Epic", image: "assets/gear/legs.png", stats: { combat: { inf_atk: 28, rng_atk: 42, army_hp: 21 }, economy: {} } },
        { id: "l7", name: "Gargantua Belt", level: 60, rarity: "Rare", image: "assets/gear/legs.png", stats: { combat: { cav_atk: 52.5, cav_hp: 38.5, army_def: 21 }, economy: { stone_prod: 70 } } },
        { id: "l8", name: "Untamed Boots", level: 55, rarity: "Epic", image: "assets/gear/legs.png", stats: { combat: { cav_atk: 28, cav_hp: 21, army_hp: 21 }, economy: { travel_speed: 42 } } },
        { id: "l9", name: "Legs of the Deceiver", level: 55, rarity: "Rare", image: "assets/gear/legs.png", stats: { combat: { rng_atk: 7, rng_def: 21, inf_atk: 16.8 }, economy: {} } },
        { id: "l10", name: "Beastly Waist Guard", level: 50, rarity: "Epic", image: "assets/gear/legs.png", stats: { combat: { cav_atk: 22.4, cav_hp: 16.8, army_def: 16.8 }, economy: {} } },
        { id: "l11", name: "Steps of Reckoning", level: 50, rarity: "Rare", image: "assets/gear/legs.png", stats: { combat: { inf_atk: 22.4, inf_def: 16.8, army_hp: 11.2 }, economy: {} } },
        { id: "l12", name: "Stealthy Steps", level: 50, rarity: "Rare", image: "assets/gear/legs.png", stats: { combat: { rng_atk: 22.4, rng_def: 28, army_hp: 11.2 }, economy: {} } }
    ],
    "armor": [
        { id: "a1", name: "Champion Plate", level: 60, rarity: "Legendary", image: "assets/gear/armor.png", stats: { combat: { rng_atk: 56, army_def: 59.5, army_hp: 35 }, economy: { reduce_upkeep: 72.8 } } },
        { id: "a2", name: "Terror Shield", level: 60, rarity: "Legendary", image: "assets/gear/armor.png", stats: { combat: { inf_atk: 49, inf_hp: 35, army_hp: 29 }, economy: { research_speed: 11.2 } } },
        { id: "a3", name: "Firewall Plate", level: 60, rarity: "Epic", image: "assets/gear/armor.png", stats: { combat: { inf_atk: 28, cav_atk: 42, siege_atk: 42, army_hp: 21 }, economy: {} } },
        { id: "a4", name: "Champion Mail", level: 60, rarity: "Legendary", image: "assets/gear/armor.png", stats: { combat: { inf_atk: 42, army_atk: 14, army_def: 49, army_hp: 21 }, economy: { reduce_upkeep: 72.8 } } },
        { id: "a5", name: "Champion Cuirass", level: 60, rarity: "Legendary", image: "assets/gear/armor.png", stats: { combat: { cav_atk: 42, army_atk: 14, army_def: 49, army_hp: 21 }, economy: { reduce_upkeep: 72.8 } } },
        { id: "a6", name: "Beastly Breastplate", level: 60, rarity: "Epic", image: "assets/gear/armor.png", stats: { combat: { rng_atk: 49, rng_hp: 21, army_def: 28 }, economy: {} } },
        { id: "a7", name: "Hardened Carapace", level: 55, rarity: "Epic", image: "assets/gear/armor.png", stats: { combat: { rng_atk: 35, cav_atk: 35, army_def: 14 }, economy: {} } },
        { id: "a8", name: "Hedonic Cuirass", level: 55, rarity: "Epic", image: "assets/gear/armor.png", stats: { combat: { inf_atk: 35, rng_atk: 35, inf_hp: 42 }, economy: {} } },
        { id: "a9", name: "Frostwing Armor", level: 50, rarity: "Rare", image: "assets/gear/armor.png", stats: { combat: { inf_atk: 11.2, rng_atk: 11.2, siege_atk: 17.5 }, economy: {} } },
        { id: "a10", name: "Winter Parka", level: 50, rarity: "Rare", image: "assets/gear/armor.png", stats: { combat: { inf_atk: 17.5, cav_def: 35, army_hp: 21 }, economy: {} } },
        { id: "a11", name: "Deadly Mantle", level: 50, rarity: "Rare", image: "assets/gear/armor.png", stats: { combat: { rng_atk: 28, trap_atk: 28, army_def: 21 }, economy: {} } },
        { id: "a12", name: "Predator Pauldrons", level: 50, rarity: "Rare", image: "assets/gear/armor.png", stats: { combat: { cav_atk: 14, cav_hp: 28, army_def: 21 }, economy: { travel_speed: 35 } } }
    ],
    "helmet": [
        { id: "h1", name: "Champion Helm", level: 60, rarity: "Legendary", image: "assets/gear/helmet.png", stats: { combat: { cav_atk: 49, army_atk: 14, army_hp: 49 }, economy: { gold_prod: 105 } } },
        { id: "h2", name: "Wyrmbone Coronet", level: 60, rarity: "Legendary", image: "assets/gear/helmet.png", stats: { combat: { rng_atk: 45.5, rng_def: 28, army_hp: 17.5 }, economy: { research_speed: 14 } } },
        { id: "h3", name: "Beast Helm", level: 60, rarity: "Legendary", image: "assets/gear/helmet.png", stats: { combat: { inf_atk: 42, cav_atk: 35, army_hp: 21 }, economy: { travel_speed: 49 } } },
        { id: "h4", name: "Bubble Helm", level: 60, rarity: "Epic", image: "assets/gear/helmet.png", stats: { combat: { rng_atk: 42, cav_atk: 42, army_hp: 28 }, economy: {} } },
        { id: "h5", name: "Champion Visor", level: 60, rarity: "Legendary", image: "assets/gear/helmet.png", stats: { combat: { inf_atk: 35, rng_atk: 35, army_atk: 14, army_hp: 28 }, economy: { gold_prod: 105 } } },
        { id: "h6", name: "Champion Armet", level: 60, rarity: "Legendary", image: "assets/gear/helmet.png", stats: { combat: { rng_atk: 35, cav_atk: 35, army_atk: 14, army_hp: 28 }, economy: { gold_prod: 105 } } },
        { id: "h7", name: "Serpent Helm", level: 60, rarity: "Epic", image: "assets/gear/helmet.png", stats: { combat: { inf_atk: 42, rng_atk: 42, inf_hp: 21, army_def: 35 }, economy: {} } },
        { id: "h8", name: "Ancient Hat", level: 55, rarity: "Epic", image: "assets/gear/helmet.png", stats: { combat: { rng_atk: 39.2, rng_def: 35, army_def: 21 }, economy: {} } },
        { id: "h9", name: "Frostwing Helm", level: 50, rarity: "Rare", image: "assets/gear/helmet.png", stats: { combat: { rng_atk: 12.6, siege_atk: 10.5, army_hp: 16.1 }, economy: {} } },
        { id: "h10", name: "Shadow Helm", level: 50, rarity: "Rare", image: "assets/gear/helmet.png", stats: { combat: { inf_atk: 14, trap_atk: 42, trap_def: 42 }, economy: { wall_def_boost: 21 } } },
        { id: "h11", name: "Devourer Helm", level: 50, rarity: "Rare", image: "assets/gear/helmet.png", stats: { combat: { inf_atk: 18.2, cav_atk: 18.2, inf_hp: 7 }, economy: {} } }
    ],
    "main_hand": [
        { id: "m1", name: "Champion Blade", level: 60, rarity: "Legendary", image: "assets/gear/main_hand.png", stats: { combat: { inf_atk: 28, rng_atk: 28, army_atk: 21, army_def: 23.8 }, economy: { research_speed: 21 } } },
        { id: "m2", name: "Champion GreatSword", level: 60, rarity: "Legendary", image: "assets/gear/main_hand.png", stats: { combat: { rng_atk: 28, cav_atk: 28, army_atk: 21, army_def: 23.8 }, economy: { research_speed: 21 } } },
        { id: "m3", name: "Champion Blade (Cav)", level: 60, rarity: "Legendary", image: "assets/gear/main_hand.png", stats: { combat: { cav_atk: 49, army_atk: 21, army_def: 23.8 }, economy: { research_speed: 21 } } },
        { id: "m4", name: "Frostwing Sword", level: 60, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { inf_atk: 28, cav_atk: 28, rng_atk: 17.5 }, economy: {} } },
        { id: "m5", name: "Skull Crasher", level: 60, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { rng_atk: 21, inf_def: 35, army_atk: 28 }, economy: {} } },
        { id: "m6", name: "Ghostly Cane", level: 60, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { inf_atk: 45.5, inf_hp: 14, army_def: 14 }, economy: {} } },
        { id: "m7", name: "Eon Axe", level: 60, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { cav_atk: 52.5, cav_def: 14, cav_hp: 14 }, economy: {} } },
        { id: "m8", name: "Terror Slash", level: 55, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { inf_atk: 38.5, inf_def: 14, army_capacity: 28 }, economy: { construction_speed: 14 } } },
        { id: "m9", name: "Horn Cudgel", level: 55, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { cav_atk: 42, cav_def: 21, trap_def: 49 }, economy: {} } },
        { id: "m10", name: "Decadent Sword", level: 55, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { inf_atk: 35, rng_atk: 35, rng_def: 14, inf_hp: 14 }, economy: {} } },
        { id: "m11", name: "Nectar Orb", level: 55, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { cav_atk: 35, rng_atk: 35, cav_def: 14, rng_hp: 14 }, economy: {} } },
        { id: "m12", name: "Kraken's Anchor", level: 55, rarity: "Epic", image: "assets/gear/main_hand.png", stats: { combat: { inf_atk: 35, cav_atk: 35 }, economy: {} } }
    ],
    "off_hand": [
        { id: "o1", name: "Champion Katar", level: 60, rarity: "Legendary", image: "assets/gear/off_hand.png", stats: { combat: { rng_atk: 49, cav_atk: 42, army_def: 28 }, economy: { training_speed: 14 } } },
        { id: "o2", name: "Champion Light", level: 60, rarity: "Legendary", image: "assets/gear/off_hand.png", stats: { combat: { inf_atk: 49, cav_atk: 42, army_def: 28 }, economy: { training_speed: 14 } } },
        { id: "o3", name: "Champion Lamp", level: 60, rarity: "Legendary", image: "assets/gear/off_hand.png", stats: { combat: { inf_atk: 49, rng_atk: 42, army_def: 28 }, economy: { training_speed: 14 } } },
        { id: "o4", name: "Winter Mitts", level: 60, rarity: "Epic", image: "assets/gear/off_hand.png", stats: { combat: { rng_atk: 14, inf_def: 45.5, army_def: 35, army_hp: 35 }, economy: {} } },
        { id: "o5", name: "Eternal Codex", level: 60, rarity: "Epic", image: "assets/gear/off_hand.png", stats: { combat: { cav_atk: 28, rng_atk: 49, cav_hp: 28 }, economy: {} } },
        { id: "o6", name: "Lunar Boomerang", level: 60, rarity: "Epic", image: "assets/gear/off_hand.png", stats: { combat: { cav_atk: 42, cav_def: 21, army_hp: 21 }, economy: {} } },
        { id: "o7", name: "Eerie Lantern", level: 60, rarity: "Epic", image: "assets/gear/off_hand.png", stats: { combat: { inf_atk: 42, inf_def: 14, inf_hp: 14 }, economy: {} } },
        { id: "o8", name: "Spirit Axe", level: 60, rarity: "Epic", image: "assets/gear/off_hand.png", stats: { combat: { inf_atk: 35, cav_atk: 35, cav_hp: 14, army_def: 14 }, economy: {} } },
        { id: "o9", name: "Venom Blade", level: 60, rarity: "Epic", image: "assets/gear/off_hand.png", stats: { combat: { inf_atk: 35, rng_atk: 35, rng_def: 14, army_hp: 14 }, economy: {} } },
        { id: "o10", name: "Dark Aegis", level: 50, rarity: "Rare", image: "assets/gear/off_hand.png", stats: { combat: { inf_atk: 14, army_def: 14 }, economy: {} } },
        { id: "o11", name: "Dragon Fist", level: 50, rarity: "Rare", image: "assets/gear/off_hand.png", stats: { combat: { cav_atk: 30.8, army_hp: 28 }, economy: {} } },
        { id: "o12", name: "Viral SwitchBlade", level: 50, rarity: "Rare", image: "assets/gear/off_hand.png", stats: { combat: { inf_atk: 21, rng_atk: 21, siege_atk: 35, siege_def: 28 }, economy: {} } }
    ],
    "accessory": [
        { id: "ac1", name: "Champion Faith", level: 60, rarity: "Legendary", image: "assets/gear/accessory.png", stats: { combat: { inf_atk: 21, cav_atk: 21, army_atk: 14, army_hp: 35 }, economy: {} } },
        { id: "ac2", name: "Ambrosial Cup", level: 60, rarity: "Legendary", image: "assets/gear/accessory.png", stats: { combat: { inf_atk: 35, rng_atk: 35, inf_hp: 21, rng_hp: 21 }, economy: {} } },
        { id: "ac3", name: "Champion Valor", level: 60, rarity: "Legendary", image: "assets/gear/accessory.png", stats: { combat: { cav_atk: 21, rng_atk: 21, army_atk: 14, army_hp: 35 }, economy: {} } },
        { id: "ac4", name: "Champion Blessing", level: 60, rarity: "Legendary", image: "assets/gear/accessory.png", stats: { combat: { inf_atk: 21, rng_atk: 21, army_atk: 14, army_hp: 35 }, economy: {} } },
        { id: "ac5", name: "Rowdy Resolve", level: 60, rarity: "Epic", image: "assets/gear/accessory.png", stats: { combat: { cav_atk: 35, cav_def: 10.5, cav_hp: 14 }, economy: {} } },
        { id: "ac6", name: "Book of the Dead", level: 60, rarity: "Mythic", image: "assets/gear/accessory.png", stats: { combat: { inf_atk: 35, cav_atk: 35, cav_def: 28, inf_hp: 21 }, economy: {} } },
        { id: "ac7", name: "Polar Ring", level: 60, rarity: "Epic", image: "assets/gear/accessory.png", stats: { combat: { cav_atk: 35, rng_atk: 35, cav_hp: 21, rng_hp: 21 }, economy: {} } },
        { id: "ac8", name: "Blight Ring", level: 60, rarity: "Legendary", image: "assets/gear/accessory.png", stats: { combat: { rng_atk: 19.6, army_def: 21, army_hp: 21 }, economy: { wall_def_boost: 35 } } },
        { id: "ac9", name: "Frostwing's Breath", level: 55, rarity: "Rare", image: "assets/gear/accessory.png", stats: { combat: { inf_atk: 11.2, cav_atk: 11.2 }, economy: { gold_prod: 70 } } },
        { id: "ac10", name: "Burning Scroll", level: 55, rarity: "Rare", image: "assets/gear/accessory.png", stats: { combat: { army_atk: 12.6, army_hp: 12.6 }, economy: { timber_prod: 49 } } },
        { id: "ac11", name: "Dragon's Iris", level: 55, rarity: "Rare", image: "assets/gear/accessory.png", stats: { combat: { cav_atk: 14, rng_atk: 14, army_hp: 14 }, economy: {} } },
        { id: "ac12", name: "Wyrm Seal", level: 55, rarity: "Rare", image: "assets/gear/accessory.png", stats: { combat: { rng_atk: 22.4, siege_atk: 21, army_hp: 11.2 }, economy: { stone_prod: 49 } } },
        { id: "ac13", name: "Terror Vial", level: 50, rarity: "Rare", image: "assets/gear/accessory.png", stats: { combat: { inf_atk: 22.4, inf_hp: 7, army_def: 11.2 }, economy: { ore_prod: 49 } } },
        { id: "ac14", name: "Fear Drum", level: 50, rarity: "Rare", image: "assets/gear/accessory.png", stats: { combat: { cav_atk: 22.4, siege_atk: 14, cav_hp: 7.7 }, economy: { gold_prod: 49 } } },
        { id: "ac15", name: "Coil Armband", level: 50, rarity: "Rare", image: "assets/gear/accessory.png", stats: { combat: { inf_atk: 18.2, rng_atk: 18.2, inf_def: 14, rng_hp: 11.2 }, economy: {} } }
    ]
};
